[package]
name = "trustfall_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
trustfall_core = { path = "../trustfall_core" }
quote = "1.0"
syn = "1.0"